'Subreddit' object has no attribute 'n_subRed' 2018-09-26 15:36:10.661174'Subreddit' object has no attribute 'n_subRed' 2018-09-26 15:36:10.932377local variable 'hot_endo' referenced before assignment 2018-09-26 15:45:41.775112'Init' object has no attribute 'duration' 2018-10-02 17:19:39.836259can't compare datetime.datetime to datetime.date 2018-10-12 14:36:56.990990can't compare datetime.datetime to datetime.date 2018-10-12 14:37:59.678454can't compare datetime.datetime to datetime.date 2018-10-12 14:44:41.699142'datetime.date' object has no attribute 'date' 2018-10-12 14:48:58.306858'NoneType' object has no attribute 'fullname' 2018-10-12 15:02:36.814185'NoneType' object has no attribute 'name' 2018-10-24 18:31:04.682894'NoneType' object has no attribute 'name' 2018-10-24 18:31:37.171979'NoneType' object has no attribute 'name' 2018-10-24 18:32:08.163399name 'users_posting_in_non_endo_group' is not defined 2018-10-25 20:00:17.729134'tuple' object has no attribute 'lower' 2018-10-26 05:30:51.587463'tuple' object has no attribute 'lower' 2018-10-26 05:33:14.802573'tuple' object has no attribute 'lower' 2018-10-26 05:36:30.565053error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /comments/9qmngj/?limit=2048&sort=best&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000170BB50AC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) 2018-10-26 08:55:55.675759